### ISSUE TITLE
Wayback injected banner is interfering with beautifulsoup.

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-warc-test#19]
I will have to figure out how to make wayback play nice with engage scraper. I should not change upstream code to fix this feature.

https://github.com/hackla-engage/engage-scraper/blob/1339555100c5e4481e5d9455a1223fe53cc1fa9f/engage_scraper/scraper_logics/santamonica_scraper_logic.py#L141

```
Traceback (most recent call last):
  File "src/test_agenda_item.py", line 27, in <module>
    print(parse_agenda_item.parse_agenda_item(bs4, 3610))
  File "/Users/psuedofinnish/git_repo/engage-warc-test/src/parse_agenda_item.py", line 14, in parse_agenda_item
    return a._process_agenda(soup, meet_id)
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/src/engage-scraper/engage_scraper/scraper_logics/santamonica_scraper_logic.py", line 166, in _process_agenda
    'span', {'id': 'ContentPlaceholder1_lblMeetingDate'}).get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
Error url fetch failed: http://localhost:8080/smgov/20190709022858mp_/http://santamonicacityca.iqm2.com/Citizens/Detail_LegiFile.aspx?Frame=&MeetingID=1183&MediaPosition=&ID=3610&CssClass=
```

**Comment by eselkin** [comment]
Ted,
I should catch that error on the scraper, but maybe we can have you add a
WAYBACK env variable and have it pre-process wayback resources to get the
original content.
-Eli

**Comment by hungrymonkey** [comment]
@eselkin, I will pre-process the wayback banner.

You should not need to change the scraper because there is a bug in this project. Either way, this project is design to validate the scraper rather than the scraper work around this project bugs. The logic sounds kinda circular.
