### ISSUE TITLE
Warc is not updated for python3

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-warc-test#2]
internetarchive warc pull 26
```
Traceback (most recent call last):
  File "print_all_urls.py", line 3, in <module>
    import warc
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/warc/__init__.py", line 10, in <module>
    from .arc import ARCFile, ARCRecord, ARCHeader
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/warc/arc.py", line 7, in <module>
    import __builtin__
ModuleNotFoundError: No module named '__builtin__'
```

**Comment by hungrymonkey** [comment]
```
Traceback (most recent call last):
  File "print_all_urls.py", line 13, in <module>
    for record in f:
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/src/warc/warc/warc.py", line 403, in __iter__
    record = self.read_record()
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/src/warc/warc/warc.py", line 386, in read_record
    header = self.read_header(fileobj)
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/src/warc/warc/warc.py", line 335, in read_header
    version_line = fileobj.readline()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 406, in _read_gzip_header
    magic = self._fp.read(2)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gzip.py", line 91, in read
    self.file.read(size-self._length+read)
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/bin/../lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by hungrymonkey** [comment]
used popol1991 tree
https://github.com/hungrymonkey/warc/tree/python3_popol1991
