### ISSUE TITLE
Selenium webdriver install issues

### ISSUE THREAD

**Issue by hungrymonkey** [hackla-engage/engage-warc-test#6]
```
==> Satisfying dependencies
==> Downloading https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_mac64.zip
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'chromedriver'.
==> Installing Cask chromedriver
==> Linking Binary 'chromedriver' to '/usr/local/bin/chromedriver'.
🍺  chromedriver was successfully installed!
(venv) psuedos-MacBook-Pro:engage-warc-test psuedofinnish$ python src/archive_agenda.py 
/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "src/archive_agenda.py", line 25, in <module>
    driver = webdriver.Chrome()
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/psuedofinnish/git_repo/engage-warc-test/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.14.4 x86_64)
````

Installing selenium is always difficult

**Comment by hungrymonkey** [comment]
I had to use the beta build

homebrew/cask-versions/google-chrome-beta

**Comment by hungrymonkey** [comment]
I have to install it on my host system as a workaround. Not self-contained in virtualenv

**Comment by hungrymonkey** [comment]
this dep seems to work
https://pypi.org/project/chromedriver-binary/
https://github.com/hackla-engage/engage-warc-test/commit/dcddf25c727b4e1b82726742c0471b792b958f5d

**Comment by hungrymonkey** [comment]
https://github.com/hackla-engage/engage-warc-test/commit/dcddf25c727b4e1b82726742c0471b792b958f5d
